Repository irssi/irssi, pull requests merged in 2018-09, with the labels that each got.

#919 Use-after-frees
  src/core/modules.c
  src/core/rawlog.c
  src/core/special-vars.c
  src/fe-common/core/themes.c
  src/irc/dcc/dcc.c
Labels: auto-merge

#914 properly record line info on empty lines
  src/fe-common/core/formats.c
  src/fe-text/gui-printtext.c
  src/fe-text/textbuffer.c
Labels: auto-merge, needs testing

#917 Add a wrapper of wcwidth() that picks the best implementation
  configure.ac
  src/common.h
  src/core/Makefile.am
  src/core/core.c
  src/core/utf8.c
  src/core/utf8.h
  src/core/wcwidth-wrapper.c
  src/fe-text/gui-entry.c
  src/fe-text/gui-windows.c
  src/fe-text/term-terminfo.c
  src/fe-text/textbuffer-view.c
  src/fe-text/textbuffer-view.h
Labels: auto-merge, needs testing

#896 Don't ignore SIGWINCH when window size is unchanged
  src/fe-text/term.c
Labels: needs testing

#931 Disconnect SASL properly in case the sasl module got unloaded from server
  src/fe-common/irc/fe-sasl.c
  src/irc/core/irc-servers-setup.c
  src/irc/core/sasl.c
Labels: auto-merge

#929 Remove incorrectly copied automake commands from fuzzer
  src/fe-fuzz/fe-common/core/Makefile.am
  src/fe-fuzz/irc/core/Makefile.am
Labels: auto-merge

#930 fix accessing unallocated text when checking entry position
  src/fe-text/gui-entry.c
Labels: auto-merge

#939 some header fixes for C modules
  src/fe-text/Makefile.am
Labels: auto-merge

#938 Don't trigger activity on hidden lines by default
  docs/signals.txt
  src/fe-common/core/window-activity.c
  src/fe-text/textbuffer-commands.c
Labels: auto-merge

#946 fix irssi being stuck when resized very small
  src/fe-text/mainwindows.c
Labels: auto-merge

#947 Fix broken display after resizing many windows very small
  src/fe-text/mainwindows.c
Labels: auto-merge
